# Generated by Django 6.1.1 on 2026-10-02 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('contrato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contrato (IXC)')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Colaborador')),
                ('tipo', models.CharField(choices=[('TECNICO', 'Técnico'), ('AUDITOR', 'Auditor'), ('OUTRO', 'Outro')], default='TECNICO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ixc', models.IntegerField(unique=True, verbose_name='ID IXC')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('assunto', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_abertura', models.DateTimeField(blank=True, null=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('reincidencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reincidência')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='operacoes.cliente')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_executadas', to='operacoes.colaborador')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('RETRABALHO', 'Retrabalho'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Auditor')),
                ('data_auditoria', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='auditorias_realizadas', to='operacoes.colaborador')),
                ('ordem_servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='operacoes.ordemservico')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
            },
        ),
    ]
