# Generated by Django 6.1.1 on 2026-10-02 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='os_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_filhas', to='operacoes.ordemservico', verbose_name='OS Original Vinculada'),
        ),
        migrations.CreateModel(
            name='Expurgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo do Expurgo')),
                ('data_expurgo', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.CharField(default='Gestor', max_length=100, verbose_name='Quem expurgou')),
                ('ordem_servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expurgo', to='operacoes.ordemservico')),
            ],
            options={
                'verbose_name': 'Expurgo',
                'verbose_name_plural': 'Expurgos',
            },
        ),
    ]
