# Generated by Django 6.1.1 on 2026-10-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0002_ordemservico_os_original_expurgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data do Feriado')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição (Ex: Natal)')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MetaOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=2026, verbose_name='Ano')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('meta_aprovacao_auditoria', models.DecimalField(decimal_places=2, default=90.0, help_text='Ex: 90.00 para 90%', max_digits=5)),
                ('meta_reincidencia', models.DecimalField(decimal_places=2, default=5.0, help_text='Ex: 5.00 para 5%', max_digits=5)),
            ],
            options={
                'verbose_name': 'Meta Operacional',
                'verbose_name_plural': 'Metas Operacionais',
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
