# Generated by Django 6.1.1 on 2026-10-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0004_colaborador_equipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaoperacional',
            name='meta_aprovacao_auditoria',
        ),
        migrations.RemoveField(
            model_name='metaoperacional',
            name='meta_reincidencia',
        ),
        migrations.AddField(
            model_name='metaoperacional',
            name='ativacao_meta_auditoria',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Ativação: Meta Auditoria'),
        ),
        migrations.AddField(
            model_name='metaoperacional',
            name='ativacao_meta_reincidencia',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Ativação: Meta Reincidência (%)'),
        ),
        migrations.AddField(
            model_name='metaoperacional',
            name='ativacao_meta_volume',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Ativação: Meta Volume'),
        ),
        migrations.AddField(
            model_name='metaoperacional',
            name='manutencao_meta_auditoria',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Manutenção: Meta Auditoria'),
        ),
        migrations.AddField(
            model_name='metaoperacional',
            name='manutencao_meta_garantia_30d',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Manutenção: Meta Garantia 30d (%)'),
        ),
        migrations.AddField(
            model_name='metaoperacional',
            name='manutencao_meta_retrabalho',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5, verbose_name='Manutenção: Meta Retrabalho (%)'),
        ),
        migrations.AddField(
            model_name='metaoperacional',
            name='manutencao_meta_volume',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Manutenção: Meta Volume'),
        ),
    ]
