# Generated by Django 6.1.1 on 2026-10-03 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0005_remove_metaoperacional_meta_aprovacao_auditoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Equipe / Supervisor')),
                ('setor', models.CharField(choices=[('ATIVACAO', 'Ativação'), ('MANUTENCAO', 'Manutenção')], default='ATIVACAO', max_length=20)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['setor', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='equipe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipe (Antigo)'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='equipe_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicos', to='operacoes.equipe', verbose_name='Equipe / Supervisor'),
        ),
    ]
