# Generated by Django 6.1.1 on 2026-10-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0006_equipe_alter_colaborador_equipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='equipe_fk',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicos', to='operacoes.equipe', verbose_name='Equipe / Supervisor'),
        ),
    ]
