# Generated by Django 6.1.1 on 2026-10-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0007_remove_colaborador_equipe_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='equipe',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='setor',
            field=models.CharField(blank=True, choices=[('ATIVACAO', 'Ativação'), ('MANUTENCAO', 'Manutenção')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderados', to='operacoes.colaborador', verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo',
            field=models.CharField(choices=[('TECNICO', 'Técnico'), ('SUPERVISOR', 'Supervisor'), ('AUDITOR', 'Auditor'), ('OUTRO', 'Outro')], default='TECNICO', max_length=20),
        ),
        migrations.DeleteModel(
            name='Equipe',
        ),
    ]
