# Generated by Django 6.1.1 on 2026-10-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0008_remove_colaborador_equipe_colaborador_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='contratacao',
            field=models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', 'PJ')], max_length=10, null=True, verbose_name='CLT / PJ'),
        ),
    ]
