# Generated by Django 6.1.1 on 2026-10-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0010_cargo_alter_colaborador_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='setor_ixc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
