# Generated by Django 6.1.1 on 2026-10-05 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0011_ordemservico_setor_ixc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlocacaoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('setor', models.CharField(blank=True, choices=[('ATIVACAO', 'Ativação'), ('MANUTENCAO', 'Manutenção')], max_length=20, null=True)),
                ('contratacao', models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', 'PJ')], max_length=10, null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacoes.cargo')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='operacoes.colaborador')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe_no_mes', to='operacoes.colaborador')),
            ],
            options={
                'verbose_name': 'Alocação Mensal',
                'verbose_name_plural': 'Alocações Mensais',
                'unique_together': {('colaborador', 'mes', 'ano')},
            },
        ),
    ]
