# Generated by Django 5.2.17 on 2026-10-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0012_alocacaomensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='nome_setor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Setor'),
        ),
    ]
