# Generated by Django 6.1.1 on 2026-10-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0013_ordemservico_nome_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaomensal',
            name='contabiliza_indicadores',
            field=models.BooleanField(default=True, verbose_name='Contabiliza para Metas?'),
        ),
    ]
